# Step 1: Import Libraries

In [1]:
import numpy as np
import pandas as pd
from joblib import dump
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.neighbors import KNeighborsClassifier
from sklearn.metrics import accuracy_score, confusion_matrix, classification_report

# Step 2: Load the Dataset

In [2]:
data = pd.read_csv('Iris.csv')

In [5]:
data

Id  SepalLengthCm  SepalWidthCm  PetalLengthCm  PetalWidthCm  \
0      1            5.1           3.5            1.4           0.2   
1      2            4.9           3.0            1.4           0.2   
2      3            4.7           3.2            1.3           0.2   
3      4            4.6           3.1            1.5           0.2   
4      5            5.0           3.6            1.4           0.2   
..   ...            ...           ...            ...           ...   
145  146            6.7           3.0            5.2           2.3   
146  147            6.3           2.5            5.0           1.9   
147  148            6.5           3.0            5.2           2.0   
148  149            6.2           3.4            5.4           2.3   
149  150            5.9           3.0            5.1           1.8   

            Species  
0       Iris-setosa  
1       Iris-setosa  
2       Iris-setosa  
3       Iris-setosa  
4       Iris-setosa  
..              ...  
145  Iris-virginica  
146  Iris-virginica  
147  Iris-virginica  
148  Iris-virginica  
149  Iris-virginica  

[150 rows x 6 columns]

# Step 3: Split the Data

In [6]:
X = data.drop(['Species','Id'],axis=1)
y = data['Species']

In [9]:
X_train,X_test,y_train,y_test = train_test_split(X,y, test_size=0.2,random_state=42)

In [15]:
X_train

SepalLengthCm  SepalWidthCm  PetalLengthCm  PetalWidthCm
22             4.6           3.6            1.0           0.2
15             5.7           4.4            1.5           0.4
65             6.7           3.1            4.4           1.4
11             4.8           3.4            1.6           0.2
42             4.4           3.2            1.3           0.2
..             ...           ...            ...           ...
71             6.1           2.8            4.0           1.3
106            4.9           2.5            4.5           1.7
14             5.8           4.0            1.2           0.2
92             5.8           2.6            4.0           1.2
102            7.1           3.0            5.9           2.1

[120 rows x 4 columns]

# Step 4: Feature Scaling

In [13]:
scaler = StandardScaler()
X_train_scaled = scaler.fit_transform(X_train)
X_test_scaled = scaler.fit_transform(X_test)

# Step 5: Initialize and Train the Model

In [16]:
knn_model = KNeighborsClassifier(n_neighbors = 5)
knn_model.fit(X_train_scaled,y_train)

KNeighborsClassifier()

# Step 6: Make Predictions

In [19]:
y_pred_knn = knn_model.predict(X_test_scaled)

# Step 7: Evaluate the Model

In [20]:
accuracy_knn = accuracy_score(y_test, y_pred_knn)
conf_matrix_knn = confusion_matrix(y_test, y_pred_knn)
class_report_knn = classification_report(y_test, y_pred_knn)

print("K-NN Accuracy:", accuracy_knn)
print("K-NN Confusion Matrix:\n", conf_matrix_knn)
print("K-NN Classification Report:\n", class_report_knn)

K-NN Accuracy: 0.9666666666666667
K-NN Confusion Matrix:
 [[10  0  0]
 [ 0  9  0]
 [ 0  1 10]]
K-NN Classification Report:
                  precision    recall  f1-score   support

    Iris-setosa       1.00      1.00      1.00        10
Iris-versicolor       0.90      1.00      0.95         9
 Iris-virginica       1.00      0.91      0.95        11

       accuracy                           0.97        30
      macro avg       0.97      0.97      0.97        30
   weighted avg       0.97      0.97      0.97        30



In [21]:
import warnings
warnings.filterwarnings("ignore")

# Iterate over each row in the test set
for i in range(len(X_test)):
    # Extract input features for the current row
    input_features = X_test.iloc[i]
    
    # Get the actual output for the current row
    actual_output = y_test.iloc[i]
    
    # Predict the output for the current row
    input_features_scaled = scaler.transform([input_features])  # Scale input features
    predicted_output = knn_model.predict(input_features_scaled)[0]  # Predict output
    
    # Print input features, predicted output, and actual output
    print("Input Features:", input_features.values)
    print("Predicted Output:", predicted_output)
    print("Actual Output:", actual_output)
    print("------------------------------------")

Input Features: [6.1 2.8 4.7 1.2]
Predicted Output: Iris-versicolor
Actual Output: Iris-versicolor
------------------------------------
Input Features: [5.7 3.8 1.7 0.3]
Predicted Output: Iris-setosa
Actual Output: Iris-setosa
------------------------------------
Input Features: [7.7 2.6 6.9 2.3]
Predicted Output: Iris-virginica
Actual Output: Iris-virginica
------------------------------------
Input Features: [6.  2.9 4.5 1.5]
Predicted Output: Iris-versicolor
Actual Output: Iris-versicolor
------------------------------------
Input Features: [6.8 2.8 4.8 1.4]
Predicted Output: Iris-versicolor
Actual Output: Iris-versicolor
------------------------------------
Input Features: [5.4 3.4 1.5 0.4]
Predicted Output: Iris-setosa
Actual Output: Iris-setosa
------------------------------------
Input Features: [5.6 2.9 3.6 1.3]
Predicted Output: Iris-versicolor
Actual Output: Iris-versicolor
------------------------------------
Input Features: [6.9 3.1 5.1 2.3]
Predicted Output: Iris-virginica

# Step 8: Save the model to a file

In [22]:
model_filename = 'knn_model'
dump(knn_model,model_filename)
print("Model have been saved successfully")

Model have been saved successfully
